### 201 {user}
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "nickname": "test5",
    "email": "mail5@mail.sfs",
    "passwHash": "1234",
    "birthday": "2000-08-06",
    "gender": "male"
}